### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Deathspike** [weizhenye/ass-compiler#6]
I encountered the following error parsing an `.ass` file:

```
(node:19260) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at parseTag (C:\Users\Deathspike\AppData\Roaming\npm\node_modules\normalize-ssa\node_modules\ass-compiler\dist\ass-compiler.js:79:22)
    at Array.map (<anonymous>)
    at parseTags (C:\Users\Deathspike\AppData\Roaming\npm\node_modules\normalize-ssa\node_modules\ass-compiler\dist\ass-compiler.js:172:17)
    at parseText (C:\Users\Deathspike\AppData\Roaming\npm\node_modules\normalize-ssa\node_modules\ass-compiler\dist\ass-compiler.js:182:18)
    at parseDialogue (C:\Users\Deathspike\AppData\Roaming\npm\node_modules\normalize-ssa\node_modules\ass-compiler\dist\ass-compiler.js:229:22)
    at Object.parse (C:\Users\Deathspike\AppData\Roaming\npm\node_modules\normalize-ssa\node_modules\ass-compiler\dist\ass-compiler.js:315:49)
    at Object.parseSubAsync (C:\Users\Deathspike\AppData\Roaming\npm\node_modules\normalize-ssa\dist\parsers\parseSub.js:27:26)
```

This occurred on the following line in the `.ass`:

```
Comment: 0,0:02:26.00,0:02:28.12,Sign,,0,0,0,,{Cell phone display}{Top line, near battery:}No signal{Third line, after "To":}Kojou-kun{Yellow popup title:}There was an error while attempting to send.{Yellow popup body:}There was an error while attempting to send your photo. There is a problem with the server or network, or your device may have been left idling for too long.
```

And here's the file:

[badsub.zip](https://github.com/weizhenye/ass-compiler/files/6055241/badsub.zip)

I hope you can fix this one. Thank you for the awesome library!

**Comment by weizhenye** [comment]
Fixed in `v0.1.2`
